NextLayer = "NextLayer"
FirstLayer = "FirstLayer"
ThisLayer = "ThisLayer"
Version = "GlManProServer-0.0"

class __private: # simple means to keep locals private
    import os.path
    import platform
    import sys
    import ctypes

    glmanInit = False

    # We use sys.platform here instead of platform.system() to avoid
    # forking a child process that might interfere with glman
    sysnm = sys.platform
    vers = platform.python_version().split('.')
    if vers[0] < '3' and vers[1] < '7':
        raise Exception("glman_for_python requires python 2.7 or newer")
    # prior to importing the python_bridge, we need to first ensure 
    # that libglman.so is loaded so all symbol resolution takes place.
    if sysnm == 'darwin':
        ext = ".dylib"
    elif sysnm == "win32":
        ext = ".dll"
    else:
        ext = ".so"
    thisfile = os.path.abspath(__file__)
    thisdir = os.path.dirname(thisfile)
    file = os.path.join(thisdir, "..", "libglman"+ext)
    libglman = ctypes.CDLL(file, ctypes.RTLD_GLOBAL)

import glman_for_python

def Init(args=[]):
    if not __private.glmanInit:
        __private.glmanInit = True
        try:
            import sys
            appname = sys.argv[0]
        except AttributeError:
            appname = 'unknownapp'
        glman_for_python.Init([appname] + args)

def Cleanup():
    glman_for_python.Cleanup()

def ParseFile(filename, layer=FirstLayer):
    glman_for_python.ParseFile(filename, layer)

# default Rif class, simply inherits from glman module.  There
# we expect the populated RiFilter table, filled with null methods.
#class Rif(glman_for_python.Rif):
#    def __init__(self, ri):
#        Init()
#        glman_for_python.Rif.__init__(self)
#        self.m_ri = ri

def RifInit(riflist):
    glman_for_python.RifInit.__doc__
    Init()
    return glman_for_python.RifInit(riflist)

def RicFlush(marker, synch, flushmode):
    glman_for_python.RicFlush(marker, synch, flushmode)

def RicGetProgress():
    return glman_for_python.RicGetProgress()

def RicProcessCallbacks():
    glman_for_python.RicProcessCallbacks()


# Ri class exposes the Ri entrypoints defined in the glman module.
# Additionally, we intercept the Declare call to ensure a python-side
# declartion for global tokens.  We also expose python tokens for
# standard Ri tokens and vars:  RI_RGBA, RiBezierBasis, etc.
class Ri(glman_for_python.Ri):
    def __init__(self):
        Init()
        glman_for_python.Ri.__init__(self)

    def Declare(self, name, decl):
        inlinedecl = decl + " " + name
        setattr(self, name, inlinedecl)
        if glman_for_python.Ri.Declare(self, name, decl) != None:
            return inlinedecl
        else:
            return None
    
    def StandardStructureHints(self):
        import time
        import getpass
        self.ArchiveRecord(self.STRUCTURE, "RenderMan RIB-Structure 1.1")
        self.ArchiveRecord(self.STRUCTURE, "Creator glman_for_python " +                                             self.PRMAN_VERSION_STR)
        self.ArchiveRecord(self.STRUCTURE, "For " + getpass.getuser())
        self.ArchiveRecord(self.STRUCTURE, "Creation Date: " +                             time.ctime(time.time()))


    # standard constants -----------------------------------
    PRMAN_VERSION =     (19, 0, 1457856, '')
    PRMAN_VERSION_STR = '19.0'
    FALSE =             0
    TRUE =              1
    INFINITY =          9.9999999999999998e+37
    EPSILON =           1e-10
    BEZIERSTEP =        3
    BSPLINESTEP =       1
    CATMULLROMSTEP =    1
    HERMITESTEP =       2
    POWERSTEP =         4

    # standard bases and callbacks -------------------------
    BezierBasis =       'BezierBasis'
    BSplineBasis =      'BSplineBasis'
    CatmullRomBasis =   'CatmullRomBasis'
    HermiteBasis =      'HermiteBasis'
    PowerBasis =        'PowerBasis'
    BesselFilter =      'BesselFilter'
    BlackmanHarrisFilter ='BlackmanHarrisFilter'
    BoxFilter =         'BoxFilter'
    CatmullRomFilter =  'CatmullRomFilter'
    DiskFilter =        'DiskFilter'
    GaussianFilter =    'GaussianFilter'
    MitchellFilter =    'MitchellFilter'
    LanczosFilter =     'LanczosFilter'
    SeparableCatmullRomFilter ='SeparableCatmullRomFilter'
    SincFilter =        'SincFilter'
    TriangleFilter =    'TriangleFilter'
    ErrorIgnore =       'ErrorIgnore'
    ErrorPrint =        'ErrorPrint'
    ErrorPrintOnce =    'ErrorPrintOnce'
    ErrorCondAbort =    'ErrorCondAbort'
    ErrorAbort =        'ErrorAbort'
    ErrorCleanup =      'ErrorCleanup'
    ProcDelayedReadArchive ='ProcDelayedReadArchive'
    ProcRunProgram =    'ProcRunProgram'
    ProcDynamicLoad =   'ProcDynamicLoad'
    Proc2DelayedReadArchive ='Proc2DelayedReadArchive'
    Proc2DynamicLoad =  'Proc2DynamicLoad'
    SimpleBound =       'SimpleBound'
    DSOBound =          'DSOBound'

    # standard tokens --------------------------------------
    A =                 'varying float a'
    ABORT =             'uniform int abort'
    ADD =               'add'
    ADDCOVERAGE =       'uniform float addcoverage'
    AI =                'ai'
    ALGORITHM =         'uniform string algorithm'
    AMBIENTLIGHT =      'ambientlight'
    AMPLITUDE =         'uniform float amplitude'
    APERTURE =          'uniform float[4] aperture'
    ARCHIVE =           'uniform string archive'
    ATMOSPHERES =       'constant int atmospheres'
    ATRIBUTECOMBINING = 'uniform string attributecombining'
    AUTOBIAS =          'constant int autobias'
    AZ =                'az'
    AZI =               'azi'
    BACKFACETOLERANCE = 'uniform float backfacetolerance'
    BACKFACING =        'uniform int backfacing'
    BACKGROUND =        'uniform color background'
    BEAMDISTRIBUTION =  'uniform float beamdistribution'
    BESSEL =            'bessel'
    BEZIER =            'bezier'
    BIAS =              'constant float bias'
    BIAS0 =             'uniform float bias0'
    BIAS1 =             'uniform float bias1'
    BICUBIC =           'bicubic'
    BILINEAR =          'bilinear'
    BINARY =            'uniform int binary'
    BINARYFORCE =       'uniform int twiceasslowwithmoreartifacts'
    BLACK =             'black'
    BLACKMANHARRIS =    'blackman-harris'
    BLP =               'blp'
    BOUND =             'float[6] __bound'
    BOUND0 =            'float[6] __bound0'
    BOUND1 =            'float[6] __bound1'
    BOX =               'box'
    BRICKMEMORY =       'uniform int brickmemory'
    BSPLINE =           'b-spline'
    BUCKET =            'bucket'
    BUCKETSIZE =        'uniform int[2] bucketsize'
    BUCKETSTRIDE =      'uniform int[2] bucketstride'
    BUMPY =             'bumpy'
    CACHEDIFFUSECOLORS ='uniform int cachediffusecolors'
    CACHEMODE =         'uniform int __cachemode'
    CAMERA =            'uniform int camera'
    CAMERAHITMODE =     'string camerahitmode'
    CATMARK =           'catmull-clark'
    CATROM =            'catmull-rom'
    CAUSTICMAP =        'uniform string causticmap'
    CENTERED =          'uniform int centered'
    CENTERFILTER =      'uniform int centerfilter'
    CHANLIST =          'uniform string chanlist'
    CHECKNANS =         'uniform int checknans'
    CI =                'varying color Ci'
    CLAMP =             'clamp'
    CLAMPCOLOR =        'uniform float[2] clampcolor'
    CLAMPED =           'uniform string clamped'
    CLAMPINGENABLE =    'uniform int clampingenable'
    CLAMPMOTION =       'uniform int clampmotion'
    CLAMPWIDTH =        'constant int clampwidth'
    CLEARLOCALS =       'uniform int clearlocals'
    CLIPPING =          'uniform float[2] Clipping'
    CLIPPINGPLANE =     'uniform float[6] ClippingPlane'
    COLOR =             'uniform color Color'
    COLORCLAMP =        'uniform float[2] colorclamp'
    COMMENT =           'comment'
    COMPRESSION =       'uniform string compression'
    COMPRESSIONQ =      'uniform string compressionquality'
    CONDABORT =         'conditionalabort'
    CONEANGLE =         'uniform float coneangle'
    CONEDELTAANGLE =    'uniform float conedeltaangle'
    CONSTANT =          'constant'
    CONSTANTWIDTH =     'constant float constantwidth'
    CONTINUATIONBYDEFAULT ='uniform int continuationbydefault'
    COORDINATESYSTEM =  'uniform string CoordinateSystem'
    CORNER =            'corner'
    CPUTIME =           'uniform float __CPUtime'
    CREASE =            'crease'
    CROPWINDOW =        'uniform float[4] CropWindow'
    CS =                'varying color Cs'
    CUBIC =             'cubic'
    CULL =              'cull'
    CURRENT =           'current'
    DEBUG =             'uniform int debug'
    DECIMATIONRATE =    'uniform float decimationrate'
    DEEPSHADOWERROR =   'uniform float deepshadowerror'
    DEEPSHADOWMEMORY =  'uniform int deepshadowmemory'
    DEEPSHADOWSIMPLIFYERROR ='uniform float deepshadowsimplifyerror'
    DEEPSHADOWTILES =   'uniform int deepshadowtiles'
    DEFCACHE =          'uniform float defcache'
    DEFINITION =        'string definition'
    DELETELIGHTS =      'deletelights'
    DEPTHBIAS =         'uniform float depthbias'
    DEPTHCUE =          'depthcue'
    DEPTHFILTER =       'uniform string depthfilter'
    DEPTHOFFIELD =      'uniform float[3] DepthOfField'
    DERIVATIVES =       'derivatives'
    DETAIL =            'uniform float[6] Detail'
    DETAILRANGE =       'uniform float[4] DetailRange'
    DICE =              'dice'
    DICEMETHOD =        'uniform string dicemethod'
    DIFFERENCE =        'difference'
    DIFFUSE =           'uniform int diffuse'
    DIFFUSEHITMODE =    'string diffusehitmode'
    DISABLE =           'uniform int disable'
    DISABLELIGHTS =     'string disablelights'
    DISK =              'disk'
    DISPLACEMENT =      'uniform float displacement'
    DISPLACEMENTBOUND = 'displacementbound'
    DISPLACEMENTS =     'constant int displacements'
    DISPLACE_RATIOS =   'uniform float[2] displace_ratios'
    DISPLAY =           'uniform string display'
    DISPLAYEXPOSURE =   'uniform float[2] exposure'
    DISPLAYONLYEDITLIGHTS ='uniform int displayonlyeditlights'
    DISPLAYOPACITYCHAN ='uniform string opacity'
    DISPLAYQUANTIZE =   'uniform int[4] quantize'
    DISTANCE =          'uniform float distance'
    DISTANTLIGHT =      'distantlight'
    DITHER =            'uniform float dither'
    DOF =               'uniform string dof'
    DOFASPECT =         'uniform float[2] dofaspect'
    DOUBLECOMP =        'doublecomp'
    DOUBLESHADED =      'uniform int doubleshaded'
    DPDTIME =           'vertex vector dPdtime'
    DPDU =              'vertex vector dPdu'
    DPDV =              'vertex vector dPdv'
    DSOFILE =           'uniform string dsofile'
    DSOFLOAT =          'uniform float dsofloat'
    DSONAME =           'string __dsoname'
    DSOPARAM =          'uniform int dsoparam'
    DSOSTRING =         'uniform string dsostring'
    DYNAMIC =           'uniform int dynamic'
    EDGEEDIT =          'edgeedit'
    EDITLIGHTS =        'string editlights'
    EMISSIONBIAS =      'constant float emissionbias'
    EMISSIONPOINTCLOUD ='uniform string emissionpointcloud'
    EMIT =              'uniform int emit'
    EMPTY =             ''
    ENABLE =            'uniform int enable'
    ENABLEGAUSSIAN =    'uniform float enable_gaussian'
    ENABLELERP =        'uniform float enable_lerp'
    ENABLELIGHTS =      'uniform string enablelights'
    ENDOFFRAME =        'uniform int endofframe'
    EPSILON1 =          'uniform float epsilon1'
    EPSILON2 =          'uniform float epsilon2'
    ESTIMATOR =         'uniform int estimator'
    EXCLUSIVE =         'exclusive'
    EXITAT =            'uniform int exitat'
    EXPOSURE =          'uniform float[2] Exposure'
    EXTRAPOLATE =       'uniform int extrapolate'
    EXTREMEDISPLACEMENT ='uniform int extremedisplacement'
    EXTREMEMOTIONDOF =  'uniform int extrememotiondof'
    EYESPLITS =         'uniform int eyesplits'
    FACEEDIT =          'faceedit'
    FACEINDEX =         '__faceindex'
    FACEVARYINGINTERPBOUNDARY ='facevaryinginterpolateboundary'
    FALLOFFPOWER =      'varying float falloffpower'
    FILE =              'constant string file'
    FILEMODE =          'uniform string filemode'
    FILENAME =          'uniform string filename'
    FILTER =            'uniform string filter'
    FILTERING =         'int filtering'
    FILTERWIDTH =       'uniform float[2] filterwidth'
    FINISHRENDERING =   'finishrendering'
    FLATNESS =          'uniform float flatness'
    FOCUSFACTOR =       'uniform float focusfactor'
    FOCUSREGION =       'uniform float focusregion'
    FOG =               'fog'
    FORCEDSAMPLING =    'uniform int forcedsampling'
    FORMATPIXELASPECTRATIO ='uniform float FormatPixelAspectRatio'
    FORMATRESOLUTION =  'uniform int[2] FormatResolution'
    FOV =               'uniform float fov'
    FRAME =             'frame'
    FRAMEASPECTRATIO =  'uniform float FrameAspectRatio'
    FRAMEBUFFER =       'constant string framebuffer'
    FRAMECAMERA =       'framecamera'
    FREQUENCYFRAMETIME ='uniform float frequencyframetime'
    FROM =              'uniform point from'
    FRUSTUM =           'uniform int frustum'
    GAUSSIAN =          'gaussian'
    GEOCACHEMEMORY =    'uniform int geocachememory'
    GEOMETRICAPPROXIMATIONFLATNESS ='uniform float GeometricApproximationFlatness'
    GEOMETRICAPPROXIMATIONFOCUSFACTOR ='uniform float GeometricApproximationFocusFactor'
    GEOMETRICAPPROXIMATIONMOTIONFACTOR ='uniform float GeometricApproximationMotionFactor'
    GLOBALMAP =         'uniform string globalmap'
    GPRIMLOG =          'uniform string[2] gprimlog'
    GPRIMSPLITS =       'uniform int gprimsplits'
    GRIDAREA =          'uniform float[2] gridarea'
    GRIDCACHESIZE =     'gridcachesize'
    GRIDMEMORY =        'uniform int gridmemory'
    GRIDS =             'grids'
    GRIDSIZE =          'uniform int gridsize'
    GROUPING =          'grouping'
    GRP_MEMBERSHIP =    'uniform string membership'
    GRP_TRACESUBSET =   'uniform string tracesubset'
    HAIR =              'uniform int hair'
    HANDLE =            'uniform string handle'
    HANDLEID =          'uniform string __handleid'
    HANDLER =           'handler'
    HEMISPHERESAMPLEMEMORY ='uniform int hemispheresamplememory'
    HERMITE =           'hermite'
    HIDDEN =            'uniform int hidden'
    HOLE =              'hole'
    I =                 'i'
    ID =                'uniform int id'
    IDENTIFIER =        'identifier'
    IGNORE =            'ignore'
    ILLUMINATEHANDLE =  'uniform string IlluminateHandle'
    IMMEDIATESUBDIVIDE ='int __immediatesubdivide'
    IMPORTANCETHRESHOLD ='importancethreshold'
    INDEXOFREFRACTION = 'uniform float indexofrefraction'
    INSIDE =            'inside'
    INTENSITY =         'uniform float intensity'
    INTERLEAVE =        'uniform string interleave'
    INTERPBOUNDARY =    'interpolateboundary'
    INTERPRETATION =    'uniform string interpretation'
    INTERSECTION =      'intersection'
    INTERSECTPRIORITY = 'uniform int intersectpriority'
    INTERVAL =          'uniform int interval'
    JITTER =            'uniform int jitter'
    KA =                'uniform float Ka'
    KD =                'uniform float Kd'
    KEEPFILES =         'uniform int keepfiles'
    KR =                'uniform float Kr'
    KS =                'uniform float Ks'
    LAGRANGIAN =        'lagrangian'
    LANCZOS =           'lanczos'
    LEVELSET =          'constant float levelset'
    LH =                'lh'
    LIGHT =             'light'
    LIGHTCOLOR =        'uniform color lightcolor'
    LIGHTING =          'lighting'
    LIMITS =            'limits'
    LINEAR =            'linear'
    LODRANGE =          'uniform int[2] lodrange'
    LOOP =              'loop'
    LPEGROUP =          'uniform string lpegroup'
    MARCH =             'uniform int march'
    MATTE =             'uniform int Matte'
    MATTEFILE =         'uniform string mattefile'
    MAXANGLE =          'uniform int maxangle'
    MAXDEPTH =          'constant int maxdepth'
    MAXDIFFUSEDEPTH =   'constant int maxdiffusedepth'
    MAXDISTANCE =       'uniform float maxdistance'
    MAXERROR =          'uniform float maxerror'
    MAXHAIRLENGTH =     'uniform int maxhairlength'
    MAXHAIRVOLUME =     'uniform int maxhairvolume'
    MAXPIXELDIST =      'uniform float maxpixeldist'
    MAXRAYDEPTH =       'constant int maxraydepth'
    MAXSPECULARDEPTH =  'constant int maxspeculardepth'
    MAXVPDEPTH =        'constant int maxvpdepth'
    MERGE =             'uniform int merge'
    METAL =             'metal'
    MIDPOINT =          'uniform int midpoint'
    MINDISTANCE =       'uniform float mindistance'
    MINMAX =            'uniform int minmax'
    MINSTOREDEPTH =     'constant int minstoredepth'
    MINWIDTH =          'constant float minwidth'
    MITCHELL =          'mitchell'
    MODE =              'string mode'
    MOTIONFACTOR =      'uniform float motionfactor'
    MPCACHE =           'uniform int mpcache'
    MPCACHEDIR =        'uniform string mpcachedir'
    MPCACHESTRIDE =     'uniform int mpcachestride'
    MPMEMORY =          'uniform int mpmemory'
    MULTIGRIDS =        'uniform int multigrids'
    N =                 'varying normal N'
    NAME =              'uniform string name'
    NDC =               'NDC'
    NEARHITHER =        'uniform float nearhither'
    NEWER =             'uniform int newer'
    NEWGROUP =          'uniform int newgroup'
    NG =                'uniform normal Ng'
    NONPERIODIC =       'nonperiodic'
    NONUNIFORM =        'uniform int nonuniform'
    NP =                'uniform normal Np'
    NURBCURVATUREDICEFACTOR ='uniform int nurbcurvaturedicefactor'
    OBJECT =            'object'
    OBJECTCACHE =       'uniform float objectcache'
    OCCLUSIONBOUND =    'uniform float occlusionbound'
    OCTREEMEMORY =      'uniform int octreememory'
    OFFSET =            'uniform float offset'
    OI =                'varying color Oi'
    OLDMOTIONFACTOR =   'uniform float oldmotionfactor'
    OPACITY =           'uniform color Opacity'
    OPACITYCACHEMEMORY ='uniform int opacitycachememory'
    OPACITYMETHOD =     'uniform string opacitymethod'
    OPACITYMULTIPLIER = 'uniform float opacitymultiplier'
    OPAQUE =            'opaque'
    ORDER =             'uniform string order'
    ORDERORIGIN =       'uniform int[2] orderorigin'
    ORIENTATION =       'uniform string Orientation'
    ORIGIN =            'uniform int[2] origin'
    ORTHOGRAPHIC =      'orthographic'
    OS =                'varying color Os'
    OTHRESHOLD =        'uniform color othreshold'
    OUTPUTALLDECLARES = 'uniform int outputalldeclares'
    OUTSIDE =           'outside'
    P =                 'vertex point P'
    PAINT =             'paint'
    PAINTEDPLASTIC =    'paintedplastic'
    PATTERN =           'uniform string pattern'
    PDISC =             'uniform int pdisc'
    PERIODIC =          'periodic'
    PERSISTENT =        'persistent'
    PERSPECTIVE =       'perspective'
    PHOTON =            'photon'
    PHOTONLIFETIME =    'uniform string photonlifetime'
    PIXELFILTERNAME =   'uniform string PixelFilterName'
    PIXELFILTERWIDTH =  'uniform float[2] PixelFilterWidth'
    PIXELSAMPLES =      'uniform float[2] PixelSamples'
    PIXELVARIANCE =     'uniform float PixelVariance'
    PLANARPROJECTION =  'uniform string planarprojection'
    PLASTIC =           'plastic'
    POINTFALLOFFPOWER = 'uniform float pointfalloffpower'
    POINTLIGHT =        'pointlight'
    POINTMEMORY =       'uniform int pointmemory'
    POWER =             'power'
    PREBIAS =           'uniform float prebias'
    PRECISION =         'uniform int precision'
    PRESERVECV =        'uniform int preservecv'
    PRIMITIVE =         'primitive'
    PRINT =             'uniform int print'
    PRINTONCE =         'printonce'
    PROCEDURAL =        'uniform string procedural'
    PROJECTIONFOV =     'uniform float ProjectionFOV'
    PROJECTIONNAME =    'uniform string ProjectionName'
    PT =                'vertex float Pt'
    PTEXTUREMAXFILES =  'uniform int ptexturemaxfiles'
    PTEXTUREMEMORY =    'uniform int ptexturememory'
    PVN =               'uniform float[4] pvn'
    PW =                'vertex hpoint Pw'
    PYRAMID =           'uniform int pyramid'
    PYRAMIDENABLE =     'uniform int pyramidenable'
    PZ =                'vertex float Pz'
    QUANTIZEDITHER =    'uniform float QuantizeDither'
    QUANTIZERANGE =     'uniform int[3] QuantizeRange'
    QUANTIZETYPE =      'uniform string QuantizeType'
    R =                 'r'
    RADIOSITYCACHEMEMORY ='uniform int radiositycachememory'
    RADIOSITYCACHEOMITMINUSONE ='uniform int radiositycacheomitminusone'
    RADIUS =            'varying float radius'
    RASTER =            'raster'
    RASTERORIENT =      'uniform int rasterorient'
    RAYDEPTH =          'constant int raydepth'
    RAY_KAYJIYA =       'kay-kajiya'
    RAY_LIST =          'list'
    RAY_TREE =          'tree'
    REFLECTION =        'uniform int reflection'
    REFWARNING =        'uniform int refwarning'
    RELATIVEDETAIL =    'uniform float RelativeDetail'
    RELATIVESHADINGRATE ='uniform float relativeshadingrate'
    RELIGHTING =        'relighting'
    REMAP =             'constant float[3] remap'
    RENDER =            'Ri:render'
    RENDERMEMORY =      'uniform float rendermemory'
    RENDERNULL =        'Ri:rendernull'
    RENDERTIME =        'uniform int rendertime'
    REPELFILE =         'uniform string repelfile'
    REPELPARAMS =       'uniform float repelparams'
    RERENDERBAKEDBDIR = 'uniform string rerenderbakedbdir'
    RESETRELATIVESHADINGRATE ='uniform float resetrelativeshadingrate'
    RESIZE =            'uniform string resize'
    RESOLUTION =        'uniform float[2] resolution'
    RESOLUTIONUNIT =    'uniform string resolutionunit'
    RESOURCE =          'uniform string resource'
    REVERSEORIENTATION ='uniform int ReverseOrientation'
    REVERSESIGN =       'uniform int reversesign'
    RGB =               'rgb'
    RGBA =              'rgba'
    RGBAI =             'rgbai'
    RGBAZ =             'rgbaz'
    RGBAZI =            'rgbazi'
    RGBI =              'rgbi'
    RGBZ =              'rgbz'
    RGBZI =             'rgbzi'
    RH =                'rh'
    RIB =               'rib'
    RIBPARSE =          'ribparse'
    RIFCONTROL =        'rifcontrol'
    RIXPLUGIN =         'uniform string rixplugin'
    ROUGHNESS =         'uniform float roughness'
    ROWSPERSTRIP =      'uniform string rowsperstrip'
    RUNFLAGS =          '_runflags'
    S =                 'varying float s'
    SAMPLEMOTION =      'constant int samplemotion'
    SAVEDATTRIBUTES =   'string __savedattributes'
    SAVESHADERSTATE =   'uniform int saveshaderstate'
    SCOPEDCOORDINATESYSTEM ='uniform string ScopedCoordinateSystem'
    SCOPENAMES =        'scopenames'
    SCREEN =            'screen'
    SCREENWINDOW =      'uniform float[4] ScreenWindow'
    SEARCHPATH =        'searchpath'
    SENSE =             'uniform string sense'
    SEPCATROM =         'separable-catmull-rom'
    SHADE =             'shade'
    SHADEGROUPS =       'uniform int shadegroups'
    SHADEGROUPSIZEFACTOR ='uniform float shadegroupsizefactor'
    SHADEQUEUESIZEFACTOR ='uniform float shadequeuesizefactor'
    SHADER =            'uniform string shader'
    SHADERINSTANCEID =  'constant string __instanceid'
    SHADERPROFILE =     'uniform string shaderprofile'
    SHADESIZE =         'uniform int shadesize'
    SHADEWCACHE =       'shadewithcache'
    SHADING =           'shading'
    SHADINGGROUP =      'uniform string shadinggroup'
    SHADINGINTERPOLATION ='uniform string ShadingInterpolation'
    SHADINGMODEL =      'uniform string shadingmodel'
    SHADINGRATE =       'uniform float ShadingRate'
    SHADOW =            'uniform int shadow'
    SHINYMETAL =        'shinymetal'
    SHUTTER =           'uniform float[2] Shutter'
    SHUTTEROPENING =    'uniform float[2] shutteropening'
    SIDES =             'uniform int Sides'
    SIGMA =             'uniform int sigma'
    SIGMABLUR =         'uniform float sigmablur'
    SINC =              'sinc'
    SMOOTH =            'smooth'
    SMOOTHTRIANGLES =   'smoothtriangles'
    SOURCE =            'uniform string source'
    SPATIALGROUPING =   'uniform int spatialgrouping'
    SPECULAR =          'uniform int specular'
    SPECULARCOLOR =     'uniform color specularcolor'
    SPECULARHITMODE =   'string specularhitmode'
    SPECULARTHRESHOLD = 'uniform float specularthreshold'
    SPHERE =            'uniform float sphere'
    SPHERICALPROJECTION ='uniform string sphericalprojection'
    SPOTLIGHT =         'spotlight'
    SRGB =              'uniform int srgb'
    ST =                'varying float[2] st'
    STANDARD =          'standard'
    STATISTICS =        'uniform string statistics'
    STITCH =            'constant int stitch'
    STOCHASTIC =        'stochastic'
    STRATEGY =          'uniform string strategy'
    STREAMMARKER =      'streammarker'
    STRUCTURE =         'structure'
    STYLESHEET =        'uniform string stylesheet'
    SUBOCCLUSION =      'uniform int subocclusion'
    SUBPIXEL =          'uniform int subpixel'
    SUBWINDOW =         'uniform int[5] subwindow'
    SUSPENDRENDERING =  'suspendrendering'
    T =                 'varying float t'
    TEXTURE =           'uniform string texture'
    TEXTURECOORDINATES ='uniform float[8] TextureCoordinates'
    TEXTUREMEMORY =     'uniform int texturememory'
    TEXTURENAME =       'uniform string texturename'
    THREADS =           'uniform int threads'
    THRESHOLD =         'constant float __threshold'
    TIMER =             'uniform int timer'
    TO =                'uniform point to'
    TRACE =             'constant int trace'
    TRACEENABLE =       'uniform int traceenable'
    TRACEMINWIDTH =     'constant float traceminwidth'
    TRANSFORM =         'uniform matrix transform'
    TRANSIENT =         'transient'
    TRANSMISSION =      'uniform int transmission'
    TRANSMISSIONHITMODE ='string transmissionhitmode'
    TRANSPARENT =       'transparent'
    TRIANGLE =          'triangle'
    TRIM =              'trim'
    TRIMCURVE =         'trimcurve'
    TRIMDEVIATION =     'uniform float trimdeviation'
    U =                 'varying float u'
    UBASISNAME =        'constant string __ubasisname'
    UNIFORM_TRIMRANGE = 'uniform float[2] trimrange'
    UNION =             'union'
    UNKNOWN =           'unknown'
    USER =              'user'
    UVW =               'uvw'
    V =                 'varying float v'
    VARSUBST =          'string varsubst'
    VBASISNAME =        'constant string __vbasisname'
    VDMAG =             'uniform float[4] vdmag'
    VERBATIM =          'verbatim'
    VERTEXEDIT =        'vertexedit'
    VIEWFRUSTUMDISTANCE ='uniform string viewfrustumdistance'
    VISIBILITY =        'visibility'
    VISIBLEPOINTS =     'visiblepoints'
    VOLUME =            'volume'
    VOLUMEBOX =         'box'
    VOLUMECONE =        'cone'
    VOLUMECYLINDER =    'cylinder'
    VOLUMEELLIPSOID =   'ellipsoid'
    VOLUMEINTERPRETATION ='uniform string volumeinterpretation'
    VOLUMEPIXELSAMPLES ='uniform float[2] VolumePixelSamples'
    VPDEPTH =           'vpdepth'
    VPDEPTHSHADINGRATE ='uniform float vpdepthshadingrate'
    VPICOLOR =          'vpicolor'
    VPIDEPTH =          'vpidepth'
    VPIMAGE =           'vpimage'
    VPINTERIORHEURISTIC ='uniform int vpinteriorheuristic'
    VPIOBJECTID =       'vpiobjectid'
    VPRELATIVESHADINGRATE ='uniform float vprelativeshadingrate'
    VPVOLUMEINTERSECTIONS ='uniform int vpvolumeintersections'
    VPVOLUMES =         'vpvolumes'
    W =                 'w'
    WIDTH =             'varying float width'
    WORLD =             'world'
    WORLDCAMERA =       'worldcamera'
    WORLDDISTANCE =     'uniform string worlddistance'
    WRITETODISK =       'writetodisk'
    XMLFILENAME =       'uniform string xmlfilename'
    YSPLITS =           'uniform int ysplits'
    Z =                 'varying float z'
    ZBLUR =             'uniform float[6] zblur'
    ZCOMPRESSION =      'uniform string zcompression'
    ZFILE =             'uniform string zfile'
    ZI =                'zi'
    ZLERP =             'uniform int zlerp'
    ZTHRESHOLD =        'uniform color zthreshold'
